config/routes.rb
Rails.application.routes.draw do
  root 'fortunes#index'
  get 'pps/index'
  get 'toss/index'
  resources :fortunes, only: [:show] do
    member do
      get :check
    end
  end
end

app/models/fortune.rb
class Fortune < ApplicationRecord
end

app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
  include FortunesHelper
  before_action :set_date

  def index
    @mezamashi = []
    @gudetama = []
    @sukkirisu = []
    @gogototal_fortune = Gogototal.where(created_at: @date).first

    for i in 1..3 do
      @mezamashi << Mezamashi.where(created_at: @date).find_by(rank: i)
      @gudetama << Gudetama.where(created_at: @date).find_by(rank: i)
      @sukkirisu << Sukkirisu.where(created_at: @date).find_by(rank: i)
    end

    @gogo_total_no1 = Gogo.where(created_at: @date).find_by(sign: @gogototal_fortune.total_no1)
    @gogo_gold_no1 = Gogo.where(created_at: @date).find_by(sign: @gogototal_fortune.gold_no1)
    @gogo_love_no1 = Gogo.where(created_at: @date).find_by(sign: @gogototal_fortune.love_no1)
    @gogo_work_no1 = Gogo.where(created_at: @date).find_by(sign: @gogototal_fortune.work_no1)
    @gogo_health_no1 = Gogo.where(created_at: @date).find_by(sign: @gogototal_fortune.health_no1)

    overall_ranking_array = {}
    signs = ["おひつじ座", "おうし座", "ふたご座", "かに座", "しし座", "おとめ座", "てんびん座", "さそり座", "いて座", "やぎ座", "みずがめ座", "うお座"]
    signs.each do |sign|
      sum = overallRanking(sign)
      overall_ranking_array.store(sign, sum)
    end

    @overall_top3 = []

    overall_ranking_array.sort{|(sign1, sum1), (sign2, sum2)| sum2 <=> sum1}[0, 3].each do |key, value|
      @overall_top3 << key
    end

    fortune_result(@overall_top3[0])
    @meza_result_1 = @meza_result
    @gude_result_1 = @gude_result
    @gogo_result_1 = @gogo_result

    fortune_result(@overall_top3[1])
    @meza_result_2 = @meza_result
    @gude_result_2 = @gude_result
    @gogo_result_2 = @gogo_result

    fortune_result(@overall_top3[2])
    @meza_result_3 = @meza_result
    @gude_result_3 = @gude_result
    @gogo_result_3 = @gogo_result

    # ゴーゴー占い更新後の表示用
    gogo_date = Gogo.last.created_at.beginning_of_day..Gogo.last.created_at.end_of_day if Gogo.last.created_at != @date
    @gogototal_fortune = Gogototal.where(created_at: gogo_date).first
    @gogo_total_no1 = Gogo.where(created_at: gogo_date).find_by(sign: @gogototal_fortune.total_no1)
    @gogo_gold_no1 = Gogo.where(created_at: gogo_date).find_by(sign: @gogototal_fortune.gold_no1)
    @gogo_love_no1 = Gogo.where(created_at: gogo_date).find_by(sign: @gogototal_fortune.love_no1)
    @gogo_work_no1 = Gogo.where(created_at: gogo_date).find_by(sign: @gogototal_fortune.work_no1)
    @gogo_health_no1 = Gogo.where(created_at: gogo_date).find_by(sign: @gogototal_fortune.health_no1)

    # ぐでたま占い更新後の表示用
    gudetama_date = Gudetama.last.created_at.beginning_of_day..Gudetama.last.created_at.end_of_day if Gudetama.last.created_at != @date
    @gudetama = []
    for i in 1..3 do
      @gudetama << Gudetama.where(created_at: gudetama_date).find_by(rank: i)
    end
  end

  def show
    gogo_date = Gogo.last.created_at.beginning_of_day..Gogo.last.created_at.end_of_day if Gogo.last.created_at != @date
    gudetama_date = Gudetama.last.created_at.beginning_of_day..Gudetama.last.created_at.end_of_day if Gudetama.last.created_at != @date

    @sign = params_change(params[:id])
    @mezamashi_sign_fortune = Mezamashi.where(created_at: @date).find_by(sign: @sign)
    @gogo_sign_fortune = Gogo.where(created_at: gogo_date).find_by(sign: @sign)
    @gudetama_sign_fortune = Gudetama.where(created_at: gudetama_date).find_by(sign: @sign)
    @gogototal_fortune = Gogototal.where(created_at: gogo_date).first

    # 2/18 アマゾンAPI中止
    # @mezamashi_lucky_item = searchLuckyItemByAmazon(Mezamashi.where(created_at: @date).find_by(sign: @sign).lucky_point)
    # @gogo_lucky_item = searchLuckyItemByAmazon(Gogo.where(created_at: gogo_date).find_by(sign: @sign).lucky_item)
    # @gudetama_lucky_item = searchLuckyItemByAmazon(Gudetama.where(created_at: gudetama_date).find_by(sign: @sign).lucky_item)
  end

  def check
    if params[:id] == "mezamashi"
      @name = "めざまし占い"
      @fortunes = Mezamashi.where(created_at: @date).sort_by { |a| a[:id] }[0, 12].sort_by! { |a| a[:rank] }
    elsif params[:id] == "gudetama"
      @date = Gudetama.last.created_at.beginning_of_day..Gudetama.last.created_at.end_of_day if Gudetama.last.created_at != @date
      @name = "ぐでたま占い"
      @fortunes = Gudetama.where(created_at: @date).sort_by { |a| a[:id] }[0, 12].sort_by! { |a| a[:rank] }
    elsif params[:id] == "gogo"
      @date = Gogo.last.created_at.beginning_of_day..Gogo.last.created_at.end_of_day if Gogo.last.created_at != @date
      @name = "ゴーゴー星占い"
      @fortunes = Gogo.where(created_at: @date).sort_by { |a| a[:id] }[0, 12].sort_by! { |a| a[:rank] }
      @fortune_total = Gogototal.where(created_at: @date).first
    elsif params[:id] == "sukkirisu"
      @name = "スッキりす誕生月占い"
      @fortunes = Sukkirisu.where(created_at: @date).sort_by { |a| a[:id] }[0, 12].sort_by! { |a| a[:rank] }
    end
  end

  private

  def set_date
    today = Date.today.beginning_of_day..Date.today.end_of_day
    yesterday = Date.yesterday.beginning_of_day..Date.yesterday.end_of_day
    day_before_yasterday = Date.today.prev_day(2).beginning_of_day..Date.today.prev_day(2).end_of_day

    if Mezamashi.exists?(created_at: today)
      @date = today
    elsif Mezamashi.exists?(created_at: yesterday)
      @date = yesterday
    elsif Mezamashi.exists?(created_at: day_before_yasterday)
      @date = day_before_yasterday
    else
      @date = Mezamashi.last.created_at.beginning_of_day..Mezamashi.last.created_at.end_of_day
    end
  end
end

app/helpers/fortunes_helper.rb
module FortunesHelper
  def params_change(params)
    return "おひつじ座" if params == "ohitsuji"
    return "おうし座" if params == "oushi"
    return "ふたご座" if params == "futago"
    return "かに座" if params == "kani"
    return "しし座" if params == "shishi"
    return "おとめ座" if params == "otome"
    return "てんびん座" if params == "tenbin"
    return "さそり座" if params == "sasori"
    return "いて座" if params == "ite"
    return "やぎ座" if params == "yagi"
    return "みずがめ座" if params == "mizugame"
    return "うお座" if params == "uo"
  end

  def params_change_reverse(params)
    return "ohitsuji" if params == "おひつじ座"
    return "oushi" if params == "おうし座"
    return "futago" if params == "ふたご座"
    return "kani" if params == "かに座"
    return "shishi" if params == "しし座"
    return "otome" if params == "おとめ座"
    return "tenbin" if params == "てんびん座"
    return "sasori" if params == "さそり座"
    return "ite" if params == "いて座"
    return "yagi" if params == "やぎ座"
    return "mizugame" if params == "みずがめ座"
    return "uo" if params == "うお座"
  end

  def gogototal_search_no1(fortune, sign)
    @no1_array = []
    @no1_array << "総合1位" if fortune.total_no1 == sign
    @no1_array << "金運1位" if fortune.gold_no1 == sign
    @no1_array << "恋愛運1位" if fortune.love_no1 == sign
    @no1_array << "仕事運1位" if fortune.work_no1 == sign
    @no1_array << "健康運1位" if fortune.health_no1 == sign
    return @no1_array
  end

  def gudetama_hogehogenahito(rank)
    @hogehogenahito = "'ぐー'な人" if rank <= 5
    @hogehogenahito = "'でーじょうぶ'な人" if rank > 5 && rank <= 8
    @hogehogenahito = "'たいへんかも…'な人" if rank > 8 && rank <= 11
    @hogehogenahito = "'マズイかも…'な人" if rank == 12
    return @hogehogenahito
  end

  def sukkirisu_hogehogerisu(rank)
    @hogehogerisu = "超スッキりす" if rank == 1
    @hogehogerisu = "スッキりす" if rank != 1 && rank <= 6
    @hogehogerisu = "まあまあスッキりす" if rank > 6 && rank <= 11
    @hogehogerisu = "ガッカりす…" if rank == 12
    return @hogehogerisu
  end

  def img_select(sign)
    @img_url = "/assets/ohitsuji.png" if sign == "おひつじ座"
    @img_url = "/assets/oushi.png" if sign == "おうし座"
    @img_url = "/assets/futago.png" if sign == "ふたご座"
    @img_url = "/assets/kani.png" if sign == "かに座"
    @img_url = "/assets/shishi.png" if sign == "しし座"
    @img_url = "/assets/otome.png" if sign == "おとめ座"
    @img_url = "/assets/tenbin.png" if sign == "てんびん座"
    @img_url = "/assets/sasori.png" if sign == "さそり座"
    @img_url = "/assets/ite.png" if sign == "いて座"
    @img_url = "/assets/yagi.png" if sign == "やぎ座"
    @img_url = "/assets/mizugame.png" if sign == "みずがめ座"
    @img_url = "/assets/uo.png" if sign == "うお座"
    return @img_url
  end

  def month_img_select(month)
    @img_url = "/assets/month1.png" if month == 1
    @img_url = "/assets/month2.png" if month == 2
    @img_url = "/assets/month3.png" if month == 3
    @img_url = "/assets/month4.png" if month == 4
    @img_url = "/assets/month5.png" if month == 5
    @img_url = "/assets/month6.png" if month == 6
    @img_url = "/assets/month7.png" if month == 7
    @img_url = "/assets/month8.png" if month == 8
    @img_url = "/assets/month9.png" if month == 9
    @img_url = "/assets/month10.png" if month == 10
    @img_url = "/assets/month11.png" if month == 11
    @img_url = "/assets/month12.png" if month == 12
    return @img_url
  end

  def overallRanking(sign)
    sum = 0
    point = 3
    for i in 0..2 do
      sum += point if sign == @mezamashi[i].sign
      sum += point if sign == @gudetama[i].sign
      point -= 1
    end
    sum += 3 if sign == @gogo_total_no1.sign
    sum += 1 if sign == @gogo_gold_no1.sign
    sum += 1 if sign == @gogo_love_no1.sign
    sum += 1 if sign == @gogo_work_no1.sign
    sum += 1 if sign == @gogo_health_no1.sign
    return sum
  end

  def fortune_result(sign)
    @meza_result = ["f", "f", "f"]
    @gude_result = ["f", "f", "f"]
    @gogo_result = ["f", "f", "f", "f", "f"]
    for i in 0..2 do
      @meza_result[i] = "t" if sign == @mezamashi[i].sign
      @gude_result[i] = "t" if sign == @gudetama[i].sign
    end
    @gogo_result[0] = "t" if sign == @gogo_total_no1.sign
    @gogo_result[1] = "t" if sign == @gogo_gold_no1.sign
    @gogo_result[2] = "t" if sign == @gogo_love_no1.sign
    @gogo_result[3] = "t" if sign == @gogo_work_no1.sign
    @gogo_result[4] = "t" if sign == @gogo_health_no1.sign
  end

  # AMAZON API --> 2/18 アクセス数上限変更のため、中止
  # def searchLuckyItemByAmazon(lucky_item)
  #   Amazon::Ecs.configure do |options|
  #     options[:AWS_access_key_id] = ENV['AMAZON_ACCESS_KEY']
  #     options[:AWS_secret_key] = ENV['AMAZON_SECRET_KEY']
  #     options[:associate_tag] = ENV['AMAZON_ASSOCIATE_TAG']
  #   end
  #   Amazon::Ecs.debug = true
  #   amazon_lucky_items = Amazon::Ecs.item_search(
  #     lucky_item,
  #     search_index: 'All',
  #     dataType: 'script',
  #     response_group: 'ItemAttributes, Images',
  #     country:  'jp',
  #   )
  #   first_item = amazon_lucky_items.items.first
  #   if first_item == nil
  #     @lucky_item = {image: nil}
  #   else
  #     @lucky_item = {
  #       # title: first_item.get('ItemAttributes/Title'),
  #       # url: first_item.get('DetailPageURL'),
  #       image: first_item.get('MediumImage/URL')
  #     }
  #   end
  # end
end

app/views/fortunes/index.html.erb
<div class="container">
  <section id="sec00">
    <p class="top_subtitle">今朝の占い結果をまとめてチェック！</p>
    <p class="top_title">Fortune Checker</p>
    <div class="sumunic_snsIcn">
      <ul class="logo_link">
        <li class="by">©︎</li>
        <li class="supunic"><a href="https://supunic.com/">supunic</a></li>
        <li class="twitter"><a href="https://twitter.com/fortune_checker" ><i class="fab fa-twitter-square"></i></a></li>
      </ul>
    </div>
    <ul class="fortune_btn">
      <li><%= link_to "めざまし占い", check_fortune_path("mezamashi") %></li>
      <li><%= link_to "ぐでたま占い", check_fortune_path("gudetama") %></li>
      <li><%= link_to "ゴーゴー星占い", check_fortune_path("gogo") %></li>
      <li><%= link_to "スッキりす誕生月占い", check_fortune_path("sukkirisu") %></li>
    </ul>
    <p class="cover_angle_down"><a href="#sec01"><%= image_tag "arw_bottom.png" %></a></p>
  </section>
  <section id="sec01">
    <div class="select_sign_title_div">
      <p class="update_sec01"><%= simple_time(@mezamashi[0].created_at) %> 更新</p>
      <h2>Check your sign!<small class="sub_title">今朝の占いをまとめてチェック！</small></h2>
    </div>
    <div class="select_sign_div">
      <ul>
        <li><%= link_to fortune_path("ohitsuji") do %><%= image_tag "ohitsuji.png" %><p>おひつじ座</p><% end %></li>
        <li><%= link_to fortune_path("oushi") do %><%= image_tag "oushi.png" %><p>おうし座</p><% end %></li>
        <li><%= link_to fortune_path("futago") do %><%= image_tag "futago.png" %><p>ふたご座</p><% end %></li>
        <li><%= link_to fortune_path("kani") do %><%= image_tag "kani.png" %><p>かに座</p><% end %></li>
        <li><%= link_to fortune_path("shishi") do %><%= image_tag "shishi.png" %><p>しし座</p><% end %></li>
        <li><%= link_to fortune_path("otome") do %><%= image_tag "otome.png" %><p>おとめ座</p><% end %></li>
        <li><%= link_to fortune_path("tenbin") do %><%= image_tag "tenbin.png" %><p>てんびん座</p><% end %></li>
        <li><%= link_to fortune_path("sasori") do %><%= image_tag "sasori.png" %><p>さそり座</p><% end %></li>
        <li><%= link_to fortune_path("ite") do %><%= image_tag "ite.png" %><p>いて座</p><% end %></li>
        <li><%= link_to fortune_path("yagi") do %><%= image_tag "yagi.png" %><p>やぎ座</p><% end %></li>
        <li><%= link_to fortune_path("mizugame") do %><%= image_tag "mizugame.png" %><p>みずがめ座</p><% end %></li>
        <li><%= link_to fortune_path("uo") do %><%= image_tag "uo.png" %><p>うお座</p><% end %></li>
      </ul>
    </div>
  </section>
  <section id="sec02">
    <div class="overall_ranking_title_div">
      <p class="update_sec02"><%= simple_time(@mezamashi[0].created_at) %> 更新</p>
      <h2>Today's Top3<small class="sub_title">星座占い総合ランキング</small></h2>
    </div>
    <div class="overall_ranking_div">
      <ul>
        <div class="top3_ranking_div">
          <%= link_to fortune_path(params_change_reverse(@overall_top3[0])) do %>
            <li class="ranking_img"><%= image_tag img_select(@overall_top3[0]) %></li>
            <li class="ranking_no1"><%= @overall_top3[0] %></li>
            <div class="ranking_div_about">
              <% @meza_result_1.each_with_index do |result, index| %>
                <% if result == "t" %>
                  <li class="meza_rank">めざまし<%= index+1 %>位</li>
                <% end %>
              <% end %>
              <% @gude_result_1.each_with_index do |result, index| %>
                <% if result == "t" %>
                  <li class="gude_rank">ぐでたま<%= index+1 %>位</li>
                <% end %>
              <% end %>
              <% @gogo_result_1.each_with_index do |result, index| %>
                <% if result == "t"  && index == 0 %>
                  <li class="gogo_rank_total">ゴーゴー総合1位</li>
                <% elsif result == "t"  && index == 1 %>
                  <li class="gogo_rank_gold">ゴーゴー金運1位</li>
                <% elsif result == "t"  && index == 2 %>
                  <li class="gogo_rank_love">ゴーゴー恋愛運1位</li>
                <% elsif result == "t"  && index == 3 %>
                  <li class="gogo_rank_work">ゴーゴー仕事運1位</li>
                <% elsif result == "t"  && index == 4 %>
                  <li class="gogo_rank_health">ゴーゴー健康運1位</li>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="top3_ranking_div">
          <%= link_to fortune_path(params_change_reverse(@overall_top3[1])) do %>
            <li class="ranking_img"><%= image_tag img_select(@overall_top3[1]) %></li>
            <li class="ranking_no2"><%= @overall_top3[1] %></li>
            <div class="ranking_div_about">
              <% @meza_result_2.each_with_index do |result, index| %>
                <% if result == "t" %>
                  <li>めざまし<%= index+1 %>位</li>
                <% end %>
              <% end %>
              <% @gude_result_2.each_with_index do |result, index| %>
                <% if result == "t" %>
                  <li>ぐでたま<%= index+1 %>位</li>
                <% end %>
              <% end %>
              <% @gogo_result_2.each_with_index do |result, index| %>
                <% if result == "t"  && index == 0 %>
                  <li>ゴーゴー総合1位</li>
                <% elsif result == "t"  && index == 1 %>
                  <li>ゴーゴー金運1位</li>
                <% elsif result == "t"  && index == 2 %>
                  <li>ゴーゴー恋愛運1位</li>
                <% elsif result == "t"  && index == 3 %>
                  <li>ゴーゴー仕事運1位</li>
                <% elsif result == "t"  && index == 4 %>
                  <li>ゴーゴー健康運1位</li>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="top3_ranking_div">
          <%= link_to fortune_path(params_change_reverse(@overall_top3[2])) do %>
            <li class="ranking_img"><%= image_tag img_select(@overall_top3[2]) %></li>
            <li class="ranking_no3"><%= @overall_top3[2] %></li>
            <div class="ranking_div_about">
              <% @meza_result_3.each_with_index do |result, index| %>
                <% if result == "t" %>
                  <li>めざまし<%= index+1 %>位</li>
                <% end %>
              <% end %>
              <% @gude_result_3.each_with_index do |result, index| %>
                <% if result == "t" %>
                  <li>ぐでたま<%= index+1 %>位</li>
                <% end %>
              <% end %>
              <% @gogo_result_3.each_with_index do |result, index| %>
                <% if result == "t"  && index == 0 %>
                  <li>ゴーゴー総合1位</li>
                <% elsif result == "t"  && index == 1 %>
                  <li>ゴーゴー金運1位</li>
                <% elsif result == "t"  && index == 2 %>
                  <li>ゴーゴー恋愛運1位</li>
                <% elsif result == "t"  && index == 3 %>
                  <li>ゴーゴー仕事運1位</li>
                <% elsif result == "t"  && index == 4 %>
                  <li>ゴーゴー健康運1位</li>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      </ul>
    </div>
  </section>
  <section id="sec03">
    <div class="ranking_title_div">
      <h2>Ranking<small class="sub_title">占い別ランキング一覧</small></h2>
    </div>
    <div class="ranking_div">
      <div class="channel mezamashi_div">
        <div class="div_text">
          <h3 class="div_title">めざまし占い</h3>
          <p class="update"><%= simple_time(@mezamashi[0].created_at) %> 更新</p>
          <ul class="about_tag">
            <li>めざましテレビ</li>
            <li>フジテレビ</li>
            <li>月〜金</li>
          </ul>
          <ul class="fortune_result">
            <li class="rank_num1"><%= @mezamashi[0].sign %></li>
            <li><p><%= @mezamashi[0].text1 %></p></li>
            <li class="rank_num2"><%= @mezamashi[1].sign %></li>
            <li><p><%= @mezamashi[1].text1 %></p></li>
            <li class="rank_num3"><%= @mezamashi[2].sign %></li>
            <li><p><%= @mezamashi[2].text1 %></p></li>
          </ul>
          <%= link_to "", check_fortune_path("mezamashi"), class: "more_btn" %>
        </div>
      </div>
      <div class="channel gudetama_div">
        <div class="div_text">
          <h3 class="div_title">ぐでたま占い</h3>
          <p class="update"><%= simple_time(@gudetama[0].created_at) %> 更新</p>
          <ul class="about_tag">
            <li>はやドキ！</li>
            <li>ＴＢＳ</li>
            <li>月〜金</li>
          </ul>
          <ul class="fortune_result">
            <li class="rank_num1"><%= @gudetama[0].sign %></li>
            <li><p><%= @gudetama[0].text %>。</p></li>
            <li class="rank_num2"><%= @gudetama[1].sign %></li>
            <li><p><%= @gudetama[1].text %>。</p></li>
            <li class="rank_num3"><%= @gudetama[2].sign%></li>
            <li><p><%= @gudetama[2].text %>。</p></li>
          </ul>
          <%= link_to "", check_fortune_path("gudetama"), class: "more_btn" %>
        </div>
      </div>
      <div class="channel gogo_div">
        <div class="div_text">
          <h3 class="div_title">ゴーゴー星占い</h3>
          <p class="update"><%= simple_time(@gogototal_fortune.created_at) %> 更新</p>
          <ul class="about_tag">
            <li>グッド！モーニング</li>
            <li>テレビ朝日</li>
            <li>月〜金</li>
          </ul>
          <ul class="gogo_fortune_result">
            <li class="gogo_gold_num1"><%= @gogototal_fortune.gold_no1 %></li>
            <li><p><%= @gogo_gold_no1.text %></p></li>
            <li class="gogo_love_num1"><%= @gogototal_fortune.love_no1 %></li>
            <li><p><%= @gogo_love_no1.text %></p></li>
            <li class="gogo_work_num1"><%= @gogototal_fortune.work_no1 %></li>
            <li><p><%= @gogo_work_no1.text %></p></li>
            <li class="gogo_health_num1"><%= @gogototal_fortune.health_no1 %></li>
            <li><p><%= @gogo_health_no1.text %></p></li>
          </ul>
          <%= link_to "", check_fortune_path("gogo"), class: "more_btn" %>
        </div>
      </div>
      <div class="channel sukkirisu_div">
        <div class="div_text last">
          <h3 class="div_title">スッキりす占い</h3>
          <p class="update"><%= simple_time(@sukkirisu[0].created_at) %> 更新</p>
          <ul class="about_tag">
            <li>スッキリ</li>
            <li>日本テレビ</li>
            <li>月〜金</li>
          </ul>
          <ul class="fortune_result">
            <li class="rank_num1"><%= @sukkirisu[0].month %>月生まれ</li>
            <li><p><%= @sukkirisu[0].text %>。</p></li>
            <li class="rank_num2"><%= @sukkirisu[1].month %>月生まれ</li>
            <li><p><%= @sukkirisu[1].text %>。</p></li>
            <li class="rank_num3"><%= @sukkirisu[2].month %>月生まれ</li>
            <li><p><%= @sukkirisu[2].text %>。</p></li>
          </ul>
          <%= link_to "", check_fortune_path("sukkirisu"), class: "more_btn" %>
        </div>
      </div>
    </div>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- Fortune Checker -->
    <ins class="adsbygoogle"
         style="display:block"
         data-ad-client="ca-pub-6929540284827971"
         data-ad-slot="2192489317"
         data-ad-format="auto"
         data-full-width-responsive="true"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
  </section>
</div>